
name: fedi-pipe
root: ~/personal/fedi_pipe

pre_window:
windows:
  - frontend:
      layout: main-vertical
      panes:
        - export COC_ENABLED="true"  && vim .
  - library:
      layout: main-vertical
      panes:
        - export COC_ENABLED="true"  && cd ../gale && vim .
  # - debugging:
  #     layout: main-vertical
  #     panes:
  #       - milk_tarot_mobile/ && flutter pub run build_runner watch --delete-conflicting-outputs
